name: ci-python-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python src/my_script.py
      - run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt 
          pytest --cov=src --cov-report=xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}